### PR TITLE
all: prepare for renaming master branch to main

### PR DESCRIPTION
**Pull request by myitcv**
Changes to make after this PR:

* [ ] (local): `git fetch origin && git push origin origin/master:refs/heads/main`
* [ ] (GitHub): change the default branch to `main`
* [ ] (GitHub): change branch protection rules from `master` to `main`
* [ ] (local): `git push origin :master`
* [ ] (local/GitHub): update all relevant wiki references

### CODE REVIEW

**Comment by myitcv** [comment]
@leitzler would appreciate your feedback too on any items to add to the above TODO list (using the description to capture that, not the commit message)

**Comment by myitcv** [comment]
A scan of the code base reveals the following instances which cannot be changed (for now) as they relate to dependencies:

```
$ git grep -i master | grep -v golang_org_x
_scripts/dockerRun.sh:61:       go get golang.org/x/tools/gopls@master golang.org/x/tools@master
cmd/govim/config/config.go:158: // https://cs.opensource.google/go/tools/+/master:gopls/doc/analyzers.md for
cmd/govim/config/config.go:159: // master).
cmd/govim/testdata/install/install_pathogen.txt:11:exec curl -LSso $HOME/.vim/autoload/pathogen.vim https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
cmd/govim/testdata/install/install_vim-plug.txt:9:exec curl -sfLo $HOME/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
github/actions/setupvim/action.yml:9:    default: 'master'
github/actions/setupvim/main.go:41:     version := "master"
```

**Comment by leitzler** [comment]
> Changes to make after this PR:
> 
> * [ ]  (local): `git fetch origin && git push origin origin/master:refs/heads/main`

Will this have the same result as running the following? (That's the way several renaming tutorials seems to suggest).
```
git branch -m master main
git push -u origin main
git remote set-head origin main
```

> * [ ]  (GitHub): change the default branch to `main`
> * [ ]  (GitHub): change branch protection rules from `master` to `main`
> * [ ]  (local): `git push origin :master`

:+1:

**Comment by myitcv** [comment]
> Will this have the same result as running the following?

That is relevant for anyone who has a local `master` branch. I don't because I do everything relative to `origin/main` as it will become.

**Comment by myitcv** [comment]
Thanks for taking a look, @leitzler - I'll make this change tomorrow.

**Comment by myitcv** [comment]
One known flake.

**Pull request merged**
