### PR TITLE
Windows

### PR DESCRIPTION
**Pull request by fiurthorn**
Adjustments to get govim run under windows.

- #1119
- #1118

### CODE REVIEW

**Comment by leitzler** [comment]
Thank you for the quick pull request! Can you please update according to the contribution guide https://github.com/govim/govim/wiki/Contributors#pull-request-contributions and we should be ready to go!

**Comment by fiurthorn** [comment]
Sorry, but won't do I. Feel free to use it or not. 
I found a bug and the developer in me wanted to fix it.
For that i created a patch ... now a PR.
But the time I took for it is used up.

Best Reagards

**Comment by leitzler** [comment]
I understand your frustration. The issue template and contribution guides are there fore a reason even if it might seem silly sometimes.

Using the templates & guides makes it easier for everyone to understand problems and suggested fixes, and as a consequence gets changes through faster since most of us work with open source code on our (limited) spare time.

Thanks for diving into this, I know that it takes both time and energy to find bugs!

**Comment by fiurthorn** [comment]
I I understand that the form is important, but I can not and do not want to dig into the creation of the PR any longer than the solution required. I don't want to continue working on the project either.
I found and fixed two errors. I'll provide the solution, that's it.

**Comment by leitzler** [comment]
No worries, what you did is appreciated.

**Pull request closed without merging**
