### PR TITLE
cmd/govim: remember previous position before GOVIMMotion call (#931)

### PR DESCRIPTION
**Pull request by roy2220**
See #931 for details

### CODE REVIEW

**Comment by myitcv** [comment]
Thanks for raising this, @roy2220 - I think we need to update the tests in https://github.com/govim/govim/blob/main/cmd/govim/testdata/scenario_default/motion.txt to reflect this change. Would you like to give that a shot?

**Comment by roy2220** [comment]
> Thanks for raising this, @roy2220 - I think we need to update the tests in https://github.com/govim/govim/blob/main/cmd/govim/testdata/scenario_default/motion.txt to reflect this change. Would you like to give that a shot?

I am sorry to say that I have moved to [vim-lsc](github.com/natebosch/vim-lsc) recently, so I'm not going to make more efforts on this.

Govim is good, but vim-lsc seems to have a bright future ahead, for it's ambitious aim to build a nice generic LSP client.

It would be exhilarating if your are going to start up a new project such as `golsc`, LSP client witten in go, I would then love to contribute to it.

**Comment by myitcv** [comment]
No problem, @roy2220. 

> for it's ambitious aim to build a nice generic LSP client.

This is, incidentally, the longer term goal of `govim` too, and to do so writing the LSP client in Go:

https://github.com/govim/govim/wiki/FAQ#why-should-i-use-govim-over-vim-govim-lsp-why-is-govim-not-language-agnostic

But per that FAQ the shorter term goal was/is to iterate quickly on the Go language with `gopls`. 

Enjoy `vim-lsc` (or did you mean `vim-lsp`?) and we may see you again soon 😄

**Comment by theclapp** [comment]
Just because @roy2220 won't be using govim any more and thus won't be updating any tests, that doesn't mean that #931, which this fixes, isn't still a bug, or that this PR shouldn't move forward (arguably, tests or no tests).

**Comment by myitcv** [comment]
@theclapp - agreed. I've just raised https://github.com/govim/govim/pull/1022 as a follow-up (couldn't update this PR because the original branch has been removed)

@roy2220 - thank you for raising the original issue and proposing a fix in this PR. I have credited you in my change.

**Pull request closed without merging**
