### PR TITLE
cmd/govim: track go.mod files

### PR DESCRIPTION
**Pull request by myitcv**
Gopls supports some features for go.mod files that can work "out of the
box" except that they are not tracked in govim -- see
https://golang.org/issue/31999. In particular, I was trying to use govim
to test hovering for go.mod files.

Add support for tracking go.mod files when they are opened in govim.

Updates #616

### CODE REVIEW

**Comment by myitcv** [comment]
@findleyr anything in particular you'd like to see tested as part of this?

**Comment by myitcv** [comment]
@leitzler this is also ready for your review when you have a sec. Thanks!

**Comment by findleyr** [comment]
Thanks for taking this over. LG.

**Review by leitzler — APPROVED** [review]
LGTM

**Comment by myitcv** [comment]
Thanks again @findleyr for kicking this off

**Pull request merged**
